### ISSUE TITLE
模板【 docker-compose.yaml 】

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#29]
```
version: "3"
services:
  nginx-service:
    image: nginx:1.17.0-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "./volume/data:/var/local"
      - "./volume/conf:/etc/nginx"
    networks:
      - djl-network
    restart: on-failure
networks:
  djl-network:
    external:
      name: djl-network
```
