### ISSUE TITLE
模板【docker-compose elk】

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#31]
```yaml
version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:6.7.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- ELASTICSEARCH_USERNAME=admin
      #- ELASTICSEARCH_PASSWORD=admin@123
    volumes:
      - "./volume/data:/usr/share/elasticsearch/data"
      - "./volume/config:/usr/share/elasticsearch/config"
    restart: always
    ports:
      - 8200:9200
      - 8300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  kibana:
    image: kibana:6.7.2
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 8201:5601
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  head:
    image: mobz/elasticsearch-head:5-alpine
    restart: always
    ports:
      - 8202:9100
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always

```
