### ISSUE TITLE
redis-compose.yaml

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#35]
```yaml
version: '3'
services:
    redis:
        image: redis:5.0-alpine
        container_name: redis
        restart: always
        ports:
            - "2001:6379"
#        entrypoint: ["redis-server","--requirepass","123456"]
        networks:
            - live-network
networks:
    live-network:
        external:
            name: live-network

```
