### ISSUE TITLE
openproject-compose.yaml

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#37]
```
[root@host1 openproject]# cat docker-compose.yaml
version: '3'
services:
  openproject:
    image: openproject/community:8
    environment:
    - SECRET_KEY_BASE=secret
    restart: always
    volumes:
    - "./volume/data:/var/openproject/pgdata"
    - "./volume/static:/var/openproject/assets"
    ports:
    - 2009:80
```
