### ISSUE TITLE
drone-compose.yaml

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#40]
```yaml
[root@host1 drone]# cat docker-compose.yaml
version: "3.0"
services:
  drone:
    image: drone/drone:1
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    environment:
      - DRONE_GITEA_SERVER=http://host2.server:2002
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_HOST=host2.server:2007
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_USER_CREATE=username:root,admin:true
      - DRONE_ADMIN=root
    ports:
      - "2007:80"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
```
