### ISSUE TITLE
eth-compose.yaml

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#42]
eth节点安装

```
version: "3"
services:
  geth-service:
    image: ethereum/client-go:alltools-v1.9.2
    ports:
      - "30303:30303"
      - "8545:8545"
    restart: always
    entrypoint: geth --rpc --rpcaddr 0.0.0.0 --rpcapi "db,eth,net,web3,miner,personal" --rpcport 8545
    volumes:
      - "./volume/data/:/root/.ethereum"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
```
