### ISSUE TITLE
gitea-compose.yaml

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#43]
```yaml
version: "3.0"
services:
  drone:
    image: gitea/gitea:1.9.5
    restart: always
#    volumes:
#      - "./data:/data"
    ports:
      - "3000:3000"
      - "2003:22"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

```
