### ISSUE TITLE
nexus-compose.yaml

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#47]
```yaml
version: '3'
services:
  nexus:
    image: sonatype/nexus3:3.19.1
    restart: always
    volumes:
      - "./volume/data:/nexus-data"
    ports:
      - 2008:8081
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

```
