### ISSUE TITLE
xxljob-compose.yaml

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#68]
1. 把xxl-job-admin的sql导入数据库
2. 创建compose并执行,

```yaml
$ cat docker-compose.yaml
version: '3'
services:
  xxl-job:
    image: "xuxueli/xxl-job-admin:2.2.0"
    restart: always
    environment:
      - "PARAMS=--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.password=123456"
    volumes:
      - "./tmp:/data/applogs"
    ports:
      - "8080:8080"
    networks:
      - local-network
networks:
  local-network:
    external:
      name: local-network
```
