### ISSUE TITLE
xxl-job

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#70]
```yml
version: '3'
services:
  xxl-job:
    image: "xuxueli/xxl-job-admin:2.2.0"
    restart: always
    environment:
      - "PARAMS=--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.password=123456"
    volumes:
      - "./tmp:/data/applogs"
    ports:
      - "8081:8080"
    networks:
      - local-network
networks:
  local-network:
    external:
      name: local-network
```
