### ISSUE TITLE
pgadmin4

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#72]
```yml
version: '3'
services:
  mysql:
    image: "dpage/pgadmin4:4.30"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "8088:80"
    networks:
      - local-network
networks:
  local-network:
    external:
      name: local-network
```
