### ISSUE TITLE
minio

### ISSUE THREAD

**Issue by fullee** [fullee/fullee.github.io#73]
```yml
version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z
    restart: always
    environment:
    - MINIO_ACCESS_KEY=FKIAIOSFOXNN7EXAMPLM
    - MINIO_SECRET_KEY=wJfalsrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEXML
    volumes:
      - "./volume/data:/data"
    ports:
      - "9000:9000"
    command: "minio server /data"
```
